project: purescript-maps-eager
version: 0.1.0
author: Joel Lefkowitz
verbose_name: PureScript maps eager
html_title: PureScript maps eager 
github_url: https://github.com/JoelLefkowitz/purescript-maps-eager
