collections:
  - common
  - purescript

excludes:
  - .cspell.json
  - README.md
  - bower.json
  - package.json
  - spago.dhall

render_context:
  project:
    name: purescript-maps-eager
    description: Eagerly evaluated functions for Maps.
    version: 0.2.0
    verbose_name: PureScript Maps Eager
    repository: https://github.com/JoelLefkowitz/purescript-maps-eager
    codacy_id: a2905892096944d49fde47dbfcb2d503

  author:
    author: joellefkowitz
    author_email: joellefkowitz@hotmail.com
    verbose_author: Joel Lefkowitz

clear_top_level: true
logical_grouping: true

loader_paths:
  - docs
