output_dir: .

clear_top_level: true
logical_grouping: true

collections:
    - common
    - purescript

loader_paths:
    - docs

protected:
    - spago.dhall

render_context:
    project:
        project_name: purescript-maps-eager
        version: 0.2.0

        verbose_name: PureScript maps eager
        description: Eagerly evaluated functions for Maps.

        repository: https://github.com/JoelLefkowitz/purescript-maps-eager
        codacy_id: a2905892096944d49fde47dbfcb2d503

        inserts:
            - usage.md

    author:
        author: Joel Lefkowitz
        author_email: joellefkowitz@hotmail.com
        author_github_handle: joellefkowitz

    package:
        is_pursuit_package: true
        package_name: maps-eager

    portfolio:
        is_portfolio: true
        status_level: 3

        languages:
            - PureScript

        paradigms:
            - Functional programming
