name: Docs

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Build the docs

        # Use npx to invoke the local spago cli
        run: npx spago docs

      - name: Upload the artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "generated-docs/html"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
