name: Review

on: [push, pull_request]

jobs:
  review:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Fetch yarn's cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Set up yarn package caching
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set the node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn global add grunt-cli
          yarn global add purescript
          yarn global add pulp
          yarn global add bower
          bower install

      - name: Run linters
        run: grunt lint

      - name: Run unit tests
        run: grunt test

      - name: Report unit test coverage
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/cobertura.xml
